### ISSUE TITLE
Feedback  - Artigo (versão inicial)

### ISSUE THREAD

**Issue by laiza-inteli** [2023M8T1Inteli/grupo4#32]
GRAMÁTICA E ESTRUTURA
-Rever a conexão entre os parágrafos (melhor detalhado abaixo, em "INTRODUÇÃO").

INTRODUÇÃO
-Inserir referência para o primeiro parágrafo, quando fala-se sobre TA.
-O artigo não explorará a evolução de TA ao longo da história. Vamos falar sobre o uso de TA para apoiar crianças com paralisia cerebral.
-Não há citações na seção de introdução.
-Melhorar a conexão entre o primeiro e segundo parágrafos. Uma sugestão é começar explicando o problema (paralisia cerebral) e depois falar sobre TA, que é uma forma de apoiar o cotidiano de crianças com PC.
-Paralisia cerebral não é mencionado em nenhum parágrafo.
-No terceiro parágrafo é citado IDE, mas o que é IDE? No parágrafo anterior é utilizado "ambiente de desenvolvimento". Uma sugestão é alterar para Ambiente de Desenvolvimento Integrado (IDE, sigla em inglês) no segundo parágrafo e depois apenas citar IDE nos parágrafos seguintes.
-Por que o problema que estamos trabalhando é relevante?
-É interessante inserirem um parágrafo sobre a AACD, conectando com a problemática e solução que estão desenvolvendo.
-Sugestão: revisar a seção. Os parágrafos não estão se conectando e não apresenta o trabalho que está sendo realizado.
-Alguns dos itens que eu trouxe estão citados no Resumo, mas é necessário que eles estejam na Introdução.

REFERÊNCIA
-Nenhuma referência é citada na introdução.
-Faltam referências para embasar o texto (exemplos inseridos em "INTRODUÇÃO").
-Inserir referências de artigos científicos ou documentos oficiais (ex.: relatório da AACD). Excluir a segunda e terceira referência.

**Comment by gbcarneiro** [comment]
#63
