### ISSUE TITLE
Feedback - Artigo (2ª versão)

### ISSUE THREAD

**Issue by laiza-inteli** [2023M8T1Inteli/grupo4#48]
INTRODUÇÃO
-As solicitações de alteração enviadas na sprint passada não foram realizadas.

TRABALHOS RELACIONADOS
-Pessoal, sobre os dois trabalhos relacionados apresentados: qual é o publico-alvo? Quais são os resultados alcançados? Precisamos de informações mais detalhadas sobre os artigos relacionados
-Apontar quais são os diferenciais do trabalho do grupo com o estudo dos autores que foram selecionados. O que o trabalho de vocês terá como contribuição que os estudos já realizados não realizaram?
-Não é usual colocar o título do artigo no decorrer do parágrafo. Usa-se a citação para referenciar isso: "vale ressaltar o estudo de Petry et al. (2018)..."

REFERÊNCIAS
-As solicitações de alteração enviadas na sprint passada não foram realizadas.
-Como a seção de Trabalhos Relacionados precisa passar por uma revisão detalhada, sugiro alterar o artigo de 2005 para um mais novo.

**Comment by gbcarneiro** [comment]
#63
